import { betterAuth } from "better-auth";
import { auroraPool } from "./db";
import { sendWelcomeEmail } from "./mailer";

/**
 * Better Auth backed by AWS Aurora PostgreSQL.
 *
 * IMPORTANT: Better Auth's adapter detection (createKyselyAdapter) recognises a
 * node-postgres Pool by checking `"connect" in database`. We therefore pass the
 * raw `pg.Pool` DIRECTLY as `database` — NOT wrapped in `{ type, pool }`, which
 * would fail detection and throw "Failed to initialize database adapter".
 *
 * The pool itself (defined in ./db.ts) authenticates to Aurora via AWS IAM:
 * a short-lived token is generated by @aws-sdk/rds-signer on every connection,
 * so there is no static database password anywhere in the system.
 */
export const auth = betterAuth({
  // Pass the pg Pool directly — Better Auth wraps it in a Kysely PostgresDialect.
  database: auroraPool,
  secret: process.env.BETTER_AUTH_SECRET,
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    minPasswordLength: 6,
  },
  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // 1 day
  },
  trustedOrigins: [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    // Vercel preview + production deployments
    ...(process.env.VERCEL_URL ? [`https://${process.env.VERCEL_URL}`] : []),
    ...(process.env.VERCEL_BRANCH_URL ? [`https://${process.env.VERCEL_BRANCH_URL}`] : []),
    ...(process.env.NEXT_PUBLIC_APP_URL ? [process.env.NEXT_PUBLIC_APP_URL] : []),
    // v0 preview URLs (vm-*.vusercontent.net) — for local testing in v0 IDE
    "https://vm-v0-yashhhyb-02a0ba0b.vusercontent.net",
  ],
  rateLimit: {
    window: 60,
    max: 20,
  },
  databaseHooks: {
    user: {
      create: {
        after: async (user) => {
          try {
            await sendWelcomeEmail(user.email, user.name ?? "there");
          } catch (err) {
            console.error("[mailer] welcome email failed:", err);
          }
        },
      },
    },
  },
});
